apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: memory-monitor
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: memory-monitor
  template:
    metadata:
      labels:
        app: memory-monitor
    spec:
      hostPID: true
      containers:
        - name: memory-checker
          image: bash:latest  # Lightweight container
          command: ["/bin/sh", "-c", "apk add --no-cache curl && chmod +x /app/memory_monitor.sh && while true; do /app/memory_monitor.sh; sleep 300; done"]
          volumeMounts:
            - name: scripts
              mountPath: /app
          resources:
            requests:
              memory: "50Mi"
              cpu: "50m"
            limits:
              memory: "100Mi"
              cpu: "100m"
      volumes:
        - name: scripts
          configMap:
            name: memory-monitor-script
      restartPolicy: Always

        

