apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-nginx-1
  labels:
    app: nginx
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: nfs-test
      containers:
        - name: nginx
          image: nginx

